ITISFoundation/osparc-simcore-clients

- osparc/api_client.py
- osparc/rest.py
- setup.py
Save binary responses to file 
-  Downloading hdf5 files raises exception: #23  
```command
pip install git+https://github.com/ITISFoundation/osparc-simcore-python-client.git@is23/fix-binary-responses
```
- upload/download an hdf5 file
- check is the right file
> Fixes download of hdf5 files

- clients/python/requirements/test.txt
Turns out `jinja2` is required to generate the html table on e2e ci. I think I managed to remove that one when doing the clean up of the imports/installs. Hence, I add it again here.
>  🐛 add jinja2 import to generate html table

- clients/python/test/e2e/ci/check_for_failures.py
- clients/python/test/e2e/ci/generate_html_table.py
- clients/python/test/e2e/ci/postprocess_e2e.py
- clients/python/test/e2e/test_files_api.py
Fix client e2e portal tests. The following are the changes:
- Don't fail postproccessing job just because one of the test runs fail. This confuses people. Instead the postprocessing job only fails if something in the postprocessing fails.
- Allow for more exitcodes from pytest to ensure tests are reported as failed when tests are interrupted.
- Ensure generated html table is compatible with above changes
> 🐛 🧪 Fix e2e client tests

- .github/workflows/publish-python-client.yml
- Makefile
- README.md
- docs/doc_entrypoint.md
- index.html
Remove direct tutorial link from main readme, since it doesn't work.
Mention direct links to API versions in doc.
- #76 
Look at new doc. Screenshot:
> 📝 Expanding doc to easier find doc for api versions

- clients/python/test/e2e/ci/e2e/e2e/preprocess.py
After adding `SecretStr` in #162 I introduced a bug in the auth for the e2e.
@elisabettai pointed out that the e2e was failing due to authentication and this is probably the reason
e2e should run now
> 🐛 fixes bad auth in e2e

- clients/python/test/e2e/test_notebooks.py
If there is not fixture defined, then it is better not to add it. Before we had
```python
def test_it( some_fixture: dict | None = None):
... 
res = using(some_fixture)
...
```
but IMO it is better to just have
```python
def test_it():
...
res = using(None)
```
At first sight, I do not see an advantage in having an undefined fixture in the test parameters. 
Fixes e2e
```cmd
file /builds/oSparc/e2e-portal-testing/osparc-simcore-clients/clients/python/test/e2e/test_notebooks.py, line 49
@pytest.mark.parametrize("notebook", all_notebooks, ids=lambda nb: nb.name)
def test_run_notebooks(tmp_path: Path, notebook: Path, params: dict[str, Any]):
E       fixture 'params' not found
>       available fixtures: _session_event_loop, anyio_backend, anyio_backend_name, anyio_backend_options, api_client, …
```
> 🐛 fixes e2e tests: missing fixture

- clients/python/client/osparc/_models.py
- clients/python/test/test_osparc/test_apis.py
- Ensure osparc variables can also be captured when the host is called `OSPARC_API_BASE_URL`.
- https://github.com/ITISFoundation/osparc-simcore/pull/5966
> 🔨 Fix capture osparc variables

- clients/python/test/e2e/conftest.py
- The latest changes to the e2e tests were not compatible with client version 0.5.0, hence the tests fail for that client version.
- This fixes the incompatibility in the tests.
> 🐛 Fix e2e tests compatibility

- clients/python/client/osparc/_files_api.py
- clients/python/client/osparc/_studies_api.py
- Change logging in client to `DEBUG` level. Main motivation is to not "pollute" the logs of the metamodeling map service too much.
> 🎨 Change to debug level logging

- .gitignore
- api/Makefile
- clients/python/src/osparc/_files_api.py
- clients/python/src/osparc/_solvers_api.py
- clients/python/src/osparc/_studies_api.py
- clients/python/test/e2e/ci/e2e/e2e/postprocess.py
- clients/python/test/e2e/conftest.py
- clients/python/test/e2e/test_solvers_api.py
- scripts/generate_version.bash
- scripts/openapi-diff.bash
- ♻️ Aligns `_dev_features` on all api before changes
- 🔨 changed versioning mechanism for [developmental releases](https://packaging.python.org/en/latest/specifications/version-specifiers/#developmental-releases) on top or a post release i.e.  `1.2.3.post3.devN` (note we use for the moment `post3`
-  🚧 _pre/post_ and _devel_ releases are **pushed to https://test.pypi.org/project/osparc/#history**
- 🔖 _final_ releases are **pushed to https://pypi.org/project/osparc/#histor**y
- 🔨 adds tooling for
- part of ITISFoundation/osparc-issues#1611
Once it is released, we can check for osparc version as
- pip considers **stable** versions are _post_ and _final_
```
pip index versions osparc -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ 
```
- To see them all
```
pip …
```
> 🔨 Changes developmental releases strategy

- clients/python/Makefile
- clients/python/test/e2e/_utils.py
IMO this is a good example of a faulty design: using `make` recipes in the unit testing code. `makefile` are close to the user and used as a tool that collect CLI options for the upper-most level user.  I would argue, base on [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) , that `makefile`  can call `pytest` but **not the other way around**
- failing e2e tests
> fixing e2e tests

- clients/python/test/tests_docs.py
- docs/doc_entrypoint.md
This PR adds tests on doc links/references:
- adds automatic tests on doc references.
- manually modified extra wrong links
- Follows up from https://github.com/ITISFoundation/osparc-simcore-clients/pull/187
Can manually run as:
```
pytest clients/python/test/tests_docs.py
```
> 🐛📝 Fixes and tests links on the doc

- docs/doc_entrypoint.md
- minor fixes in main page
- adds reference to external gh repos  and gh topic `#
> 📝 doc: new references to external resources

- clients/python/test/e2e/test_notebooks.py
- Only run wallets jupyter notebook in the e2e tests after we upgrade to pydantic v2.
- https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines/895793/test_report?job_name=python_client_e2e_test%3A+%5Blatest_master%5D
- fixes #203
> 🐛 Fix pydantic v1 nullable bug

- .github/workflows/publish-python-client.yml
- clients/python/test/e2e/test_files_api.py
- An update in the gihub action we use to publish `osparc` to Pypi seems to have broken our pipeline. So the last prelrelease packages were not pushed to pypi. The issue seems to be the new `attestation` feature (see [here](https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#generating-and-uploading-attestations) and [here](https://github.com/pypa/gh-action-pypi-publish/discussions/255#discussioncomment-10615575))
- I also filter for the `osparc` version  when checking RAM usage for file upload/download since this feature was only added recently.
- fixes #209
> 🐛 Fix e2e tests

- clients/python/test/e2e/test_files_api.py
> Fix e2e tests by not importing PaginationIterable

- clients/python/test/e2e/conftest.py
- clients/python/test/e2e/test_files_api.py
I have observed that our e2e tests sometimes fail when cleaning up, that's not intended
> 🐛 Dont fail when cleaning up

- .github/workflows/github-pages.yml
- api/Makefile
- api/openapi.json
updates the repo agains the latest changes form osparc-simcore master branch
> ⬆️ Updated clients from latest master commit

- .github/workflows/build-python-client.yml
- clients/python/src/osparc/_api_files_api.py
- clients/python/src/osparc/_api_solvers_api.py
- clients/python/src/osparc/models.py
- The many changes to `openapi.json` changed the `osparc_client` caused changes in the `osparc_client`, this corrects the wrappers in `osparc`. I have run the e2e tests locally against inhouse master to check that this fixes the current issues.
> 🐛 Fix `osparc` wrapper issues due to `openapi.json` update

- clients/python/test/e2e/conftest.py
- clients/python/test/e2e/test_solvers_api.py
- This PR fixes e2e tests after the latest release (https://github.com/ITISFoundation/osparc-simcore-clients/pull/232) of the dev version of the client.
- WARNING: The need for this PR to make tests pass show that the client has broken backwards compatibility. Hence, for the next proper release we should bump the major version of the client.
> 🐛 Fix tests after StrictStr -> UUID change in latest (dev) version of client
