- Makefile
- README.md
- code_samples/MetaApi.ipynb
- code_samples/UsersApi.ipynb
- docs/UsersApi.md
Updates some API notebooks for a faster demo
> update notebook examples

- .github/CODEOWNERS
- .github/workflows/publish-to-test-pypi.yml
- Makefile
- README.md
- docs/README.md
- osparc/__init__.py
- osparc/configuration.py
- setup.cfg
- setup.py
- git actions to package and deploy in test-pypi and pipit
- bump2version to change versioning
> New git actions to release

- .github/workflows/publish-to-test-pypi.yml
- Makefile
- README.md
- docs/README.md
- osparc/__init__.py
- osparc/configuration.py
- setup.cfg
- setup.py
- rename distribution package to osparc
- Cleaned up doc
- Removed default tagging. Needs to be done by hand
> Cleanup doc and package

- .github/workflows/deploy.yml
- README.md
- api/openapi.json
- docs/README.md
- docs/md/SolversApi.md
- osparc/__init__.py
- osparc/api/solvers_api.py
- osparc/configuration.py
- osparc/models/task_states.py
- setup.cfg
- setup.py
changes along side with PR https://github.com/ITISFoundation/osparc-simcore/pull/2220
> updates auth and task states enum

- api/openapi.json
- docs/README.md
- docs/md/BasicTutorial.md
- docs/md/tutorials/BasicTutorial.md
Introductory tutorial 
```cmd
make serve-doc
```
> doc: basic tutorial

- .github/ISSUE_TEMPLATE/ask_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- Makefile
- README.md
- requirements-dev.txt
- adds pre-commit 
- change release recipes to : ``pre-release`` and ``release``
- github issue templates
- https://github.com/ITISFoundation/osparc-issues/issues/668
- closes #30 (replaced by this PR)
-
> 🔨 Makefile release recipes, pre-commit config, doc and gh templates

- Makefile
- NOTES.md
- README.md
- 📝 fixes footer in readme
- 🔨 cleanup Makefile release recipes
- cleanup
> 📝 Maintenance/doc

- NOTES.md
- docs/md/code_samples/tutorials/BasicTutorial.ipynb
- fixes some issues with automatic conversion of notebooks
-
> 📝 updates BasicTutorial notebook

- .github/workflows/github-pages.yml
- .github/workflows/python-client-artifact.yml
Delete whitespace from names of gh actions, so they are easier to reference from command line in other repos
- https://github.com/ITISFoundation/osparc-simcore-clients/issues/40
> 🐛 delete whitespace

- clients/python/docs/BasicTutorial.ipynb
Update links in the basic tutorial.
>  📝 Update api key link basic tutorial

- clients/python/client/osparc/_files_api.py
- clients/python/client/osparc/_http_client.py
- clients/python/client/osparc/_solvers_api.py
- clients/python/client/osparc/_utils.py
Fix deserialization issue in jobs which I didn't spot before. The fix is quite ugly but all of this should be cleaned up once we upgrade the automatically generated client so that we have pydantic models
> 🐛 fix deserialization issue of pages

- clients/python/test/e2e/test_files_api.py
Enable test which can now run because the file deletion endpoint has been added on the server side. 
must be merged **after** https://github.com/ITISFoundation/osparc-simcore/pull/4707
> 🧪 enable test

- api/openapi.json
- clients/python/client/osparc/_files_api.py
- clients/python/client/osparc/_utils.py
- clients/python/test/e2e/conftest.py
- clients/python/test/e2e/test_files_api.py
- clients/python/test/test_osparc/test_osparc_client/test_file.py
- Update `openapi.json`
- Add private `search_files` function to the files api
- When uploading a file to the server, it is checked if a file with that checksum and name exists on the server. If yes, then it is returned instead of uploading a new copy
- add tests
- https://github.com/ITISFoundation/osparc-simcore-clients/issues/64
> ✨ only upload files if not already on server

- .github/PULL_REQUEST_TEMPLATE.md
Add instruction for internal devs to add labels to the PR etc.
Read the new template
> 📝  Update PULL_REQUEST_TEMPLATE.md with instructions for internal devs

- .github/workflows/publish-python-client.yml
Start using the OpenID Connect of pypi to publish the python client. This PR doesn't actually add anything, but I set up this repo as a trusted publisher in Pypi, so Pypi should issue temporary tokens. Hence, the env tokens are no longer needed. I have also removed the secrets which are no longer needed from this repo
https://github.com/ITISFoundation/osparc-simcore/issues/4807
> 🔨 setup workflow file for publishing to pypi

- CITATION.cff
Add a citation file, so it can be used to cite the "oSPARC API" e.g. in scientific papers
> 📝  Create CITATION.cff

- clients/python/test/e2e/test_studies.py
- skip studies test for latest version of released client because it holds functionality which isn't there yet
> 🐛 Fix studies test

- clients/python/client/osparc/__init__.py
- Retire deprecated python versions.
- Preparation for https://github.com/ITISFoundation/osparc-issues/issues/1517
> ✨ Prepare release 0.7.0

- clients/python/test/e2e/ci/e2e/e2e/_models.py
Allow to pass username and password in e2e tests
> ✨ Update e2e models

- clients/python/test/e2e/conftest.py
> 🐛 Fix api client construction in conftest

- clients/python/test/e2e/ci/e2e/e2e/postprocess.py
> 🔨 Improves e2e script

- Makefile
- scripts/generate_version.bash
- reset to `post0`
- some cleanup in Makefile
> 🔨 Rest development versions to `post0`

- clients/python/docs/BasicTutorial_v0.5.0.md
- clients/python/docs/BasicTutorial_v0.6.0.md
- clients/python/src/osparc/_api_client.py
- docs/doc_entrypoint.md
Some improvements based on feedback by @calys 
- updates main doc
- fixes wrong links to tutorials
- part of https://github.com/ITISFoundation/osparc-issues/issues/1611
> 📝 Enhances doc and fixes missing links

- clients/python/requirements/e2e-test.txt
- clients/python/setup.py
- clients/python/src/osparc/_api_files_api.py
- clients/python/src/osparc/_http_client.py
- clients/python/src/osparc/_utils.py
- clients/python/test/e2e/_utils.py
- clients/python/test/e2e/conftest.py
- clients/python/test/e2e/test_files_api.py
- clients/python/test/e2e/test_solvers_api.py
- clients/python/test/test_osparc/test_async_http_client.py
Ensure files are downloaded from the server in chunks in order to avoid the memory issues explained in #205 
- fixes #205 
- Run `python -m pytest -k test_upload_file` from `clients/python/test/e2e`
> 🐛 Ensure chunk file download

- clients/python/test/e2e/test_files_api.py
- Fix tests https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines/901497/test_report?job_name=python_client_e2e_test%3A+%5Bv066%5D
- fixes #207
> 🐛 Fix e2e test

- clients/python/test/e2e/test_files_api.py
- clients/python/test/e2e/test_solvers_api.py
- Fix remaining issues with e2e tests
> 🐛 Fixes to e2e tests

- clients/python/test/e2e/test_files_api.py
> 🐛 skip tests for earlier clients (e2e failing for earlier versions of the client)

- clients/python/test/e2e/test_files_api.py
> 🔨 only run a single large upload test per test run

- clients/python/requirements/e2e-test.txt
- clients/python/test/e2e/conftest.py
- clients/python/test/e2e/test_files_api.py
- Refactor e2e tests. Two main changes: One of the reasons why our e2e tests are so slow is that there are several tests which upload and download large files. This PR introduces a fixture with `scope=session` which uploads a file to the server and deletes it once the test session is over. This is then used everywhere.
- This PR also cleans `test_search` where I did some dirty exception handling which apparently has covered some undetected bugs. Hence, now the e2e tests will fail because of those bugs. They will be fixed in a follow up PR
- There is no issue, but the failing e2e tests are related.
> 🐛 ♻️ refactor e2e tests

- clients/python/src/osparc/_api_files_api.py
- clients/python/test/e2e/test_files_api.py
> 🐛 fix searchfile bug and filter tests for old clients

- api/openapi.json
- Update OAS. Relevant PRs on the server side which will go in here:
- https://github.com/ITISFoundation/osparc-simcore/pull/7900
- https://github.com/ITISFoundation/osparc-simcore/pull/7892
- @JavierGOrdonnez this will add the functionality to the client which you are missing.
> ✨update oas
